language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      addons:
         apt:
           packages:
             - libgsl-dev
             - libglib2.0-dev
    - os: osx
      osx_image: xcode10.2
      addons:
         homebrew:
           packages:
             - gsl
             - glib
script:
  - mkdir build
  - cd build
  - cmake -DENABLE_TESTING=ON ..
  - make
  - bhcd/bhcd --help 
  - ctest 
